# Generated by Django 4.2.5 on 2023-09-12 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectStatus', models.BooleanField(default=False)),
                ('projectTitle', models.CharField(max_length=255)),
                ('projectPlace', models.CharField(max_length=255)),
                ('estimatedImplementationDate', models.DateTimeField()),
                ('slogan', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('goal', models.TextField()),
                ('support', models.TextField()),
                ('shortDesc', models.CharField(max_length=200)),
                ('longDesc', models.TextField()),
                ('projectImage', models.ImageField(upload_to='project_images/')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('participantCount', models.IntegerField(default=0)),
                ('projectValue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalShares', models.IntegerField(default=0)),
                ('shareValue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('maxSharesPerPerson', models.IntegerField(default=0)),
                ('sharesTaken', models.IntegerField(default=0)),
                ('adminAdvice', models.BooleanField(default=False)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('participantList', models.ManyToManyField(blank=True, related_name='participated_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
