# Generated by Django 4.2.5 on 2023-09-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createdByName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
