# Generated by Django 4.2.5 on 2023-09-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_createdbyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimatedImplementationDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
