# Generated by Django 4.2.5 on 2023-09-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_followerlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='participantList',
        ),
    ]
