# Generated by Django 4.2.5 on 2023-09-23 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_maxsharesperperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimatedImplementationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
