# Generated by Django 4.2.5 on 2023-09-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0008_alter_project_estimatedimplementationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='project_attachments_files/')),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
            ],
        ),
    ]
