# Generated by Django 4.2.5 on 2023-09-18 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
