# Generated by Django 4.2.5 on 2023-09-20 23:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_maxsharesperperson_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share_ownership', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shareownership',
            unique_together={('user', 'project')},
        ),
    ]
